### PR TITLE
Fix: Check for `MetaProperty`s (eg `import.meta`)

### LINKED ISSUE #20: Is-Reference does not work with MetaProperty nodes (`import.meta.*`)
When parsing `import.meta.*` statements, is-reference does not check for MetaProperty nodes, and assumes that `meta` is a reference. [Here](https://svelte.dev/playground/hello-world?version=5.1.13#H4sIAAAAAAAACm2SzW6sMAyFXyVKKzVIlNlTQOrurq-6m8wiA55O1JBEjmnvKOLdrzL8jlSxIBx_Po5tIreqB17yP2CMYz8OTccEdJqgy3jOL9pA4OUxcrr5xCWB50vWu_dF-AZDSTurAL_prbMElgIveRVa1J4aaSXp3jskFr3CACO7oOvZi2od2pe3XVyHv3ABBNvCzOjwiov0gMYfZb4WJwiEAK9JApwwA8TWzMBq9hxIEYjjKVvjBP9oi0g-WRc9kCoGNJJvaHtV9hM6VjMhsrqJSZdEeJtPiVEhud1bFMk6j8EN2MLHzUMpee-6wYDk4-SanocLHk-zntoQKlAeFw4sAQrrOsi9QrCUrSFJ-iJ2c3ug9ti-WuGHcL2TRVridiFJ43KcD2M2v1tF7VUAYhbvoSkwz0Uki-qwbrxK_SsExZz9gptHCKGOMzyys7Zd-a3MAHVM5Lj7Sbbx2-qw2CTLMzbSrn2Gkk1KNZh7dnwC1V73O1dh-5q7qYxu4iZWB6On5ENKHlPJwTQ856kwLwkHGE_jfwa02bg5AwAA)'s an example in the Svelte REPL.

### PR DESCRIPTION
**Pull request by Ocean-OS**
Fixes #20. Now, the `meta` in `import.meta` will return `false` because it is not a reference. This adds tests for `MetaProperty`s as well.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ export default function is_reference (node, parent) {
 
 			// disregard the `foo` in `class {foo(){}}` but keep it in `class {[foo](){}}`
 			case 'MethodDefinition': return parent.computed;
-
+				
+			//disregard the `meta` in `import.meta`
```
Comment (Rich-Harris) [inline src/index.js]:
```suggestion
			// disregard the `meta` in `import.meta`
```

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thanks!
